{
 "title": "Petit Journal Overview Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Node Exporter Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"node-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime Prometheus",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM disponible %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}