apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: app
type: Opaque
stringData:
  mysql-root-password: "RootPassword123!"
  mysql-password: "WordPressPassword123!"
  mysql-database: "wordpress"
  mysql-user: "wordpress"