name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Valider docker-compose
        run: |
          docker compose -f docker/docker-compose.yml config

      - name: Valider docker-compose test
        run: |
          docker compose -f docker/docker-compose.test.yml config
